name: release
on:
  push:
    tags:
      - "v*"
permissions:
  contents: write

jobs:
  release:
    name: Release ${{ matrix.artifact }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            target: x86_64-apple-darwin
            artifact: darwin-amd64
          - os: macos-latest
            target: aarch64-apple-darwin
            artifact: darwin-arm64
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact: windows-amd64.exe
          - os: windows-latest
            target: aarch64-pc-windows-msvc
            artifact: windows-arm64.exe
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact: linux-amd64
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            artifact: linux-arm64

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: release-${{ matrix.target }}
      - uses: taiki-e/install-action@v2
        if: runner.os == 'Linux' && matrix.target != 'x86_64-unknown-linux-gnu'
        with:
          tool: cross
      - name: Build
        shell: bash
        run: |
          if [[ "${{ runner.os }}" == "Linux" && "${{ matrix.target }}" != "x86_64-unknown-linux-gnu" ]]; then
            cross build --release --locked --target "${{ matrix.target }}"
          else
            cargo build --release --locked --target "${{ matrix.target }}"
          fi
      - uses: cli/gh-extension-precompile@v2
        with:
          build_script_override: "script/build.sh"
        env:
          TARGET: ${{ matrix.target }}
          ARTIFACT: ${{ matrix.artifact }}
